on: [push]
jobs:
  build-and-deploy:
    env:
      REGISTRY_URL: {{#toLower}} {{{inputs.containerRegistry}}} {{/toLower}}.azurecr.io
      SERVICE_NAME: {{#sanitizeString}} {{#substring}} {{{ inputs.aksCluster.name 0 50}}} {{/substring}} {{/sanitizeString}}
      NAMESPACE: $SERVICE_NAME{{#tinyguid}}{{/tinyguid}}
      IMAGE_NAME: $SERVICE_NAME{{#tinyguid}}{{/tinyguid}}
      APP_NAME: $(SERVICE_NAME)_{{#tinyguid}}{{/tinyguid}} 
      SECRET_NAME: {{#sanitizeString}} {{#substring}} {{{ inputs.aksCluster.name 0 12}}} {{/substring}} {{/sanitizeString}}dockerauth

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: $REGISTRY_URL
        username: ${{ assets.containerRegistryUsername  }}
        password: ${{ assets.containerRegistryPassword  }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/{{ workingDirectory }}" -f  "{{ workingDirectory}}/Dockerfile" -t  $REGISTRY_URL/$IMAGE_NAME:{{=<% %>=}}${{ <% github.sha %> }}<%={{ }}=%>
        docker push $REGISTRY_URL/$IMAGE_NAME:{{=<% %>=}}${{ <% github.sha %> }}<%={{ }}=%>
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aksKubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep $NAMESPACE | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace $NAMESPACE`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: $NAMESPACE
        container-registry-url: $REGISTRY_URL
        container-registry-username: ${{ assets.containerRegistryUsername  }}
        container-registry-password: ${{ assets.containerRegistryPassword  }}
        secret-name: $SECRET_NAME
       
    - name: Generate Kubernetes Manifest file
      id: manifest-creation
      run: |
        echo  "apiVersion : apps/v1beta1
              kind: Deployment
              metadata:
                name: "$APP_NAME"
              spec:
                replicas: 2
                template:
                  metadata:
                    labels:
                      app: "$APP_NAME"
              spec:
                containers:
                  - name: "$APP_NAME"
                    image: "$REGISTRY_URL/$IMAGE_NAME"
                    ports:
                    - containerPort: {{{ inputs.containerPort }}}
                  
              {{#inputs.aksCluster.properties.addonProfiles.httpapplicationrouting.enabled}}     
              {{/inputs.aksCluster.properties.addonProfiles.httpapplicationrouting.enabled}} 

                apiVersion: v1
                kind: Service
                metadata:
                    name: "$APP_NAME"
                    labels:
                        app: "$APP_NAME"
                spec:
                    type: ClusterIP
                    ports:
                    - port: {{{ inputs.containerPort }}}
                      targetPort: {{{ inputs.containerPort }}}
                      protocol: TCP
                      name: http
                    selector:
                        app: "$APP_NAME"

                apiVersion: extensions/v1beta1
                kind: Ingress
                metadata:
                    name: "$APP_NAME"
                    labels:
                        app: "$APP_NAME"
                    annotations:
                        kubernetes.io/ingress.class: addon-http-application-routing
                spec:
                    rules:
                        - host: $NAMESPACE-$APP_NAME.{{{inputs.aksCluster.properties.fqdn}}}
                          http:
                            paths:
                            - path: /
                              backend:
                                serviceName: "$APP_NAME"
                                servicePort: {{{ inputs.containerPort }}}"
                  
              {{^inputs.aksCluster.properties.addonProfiles.httpapplicationrouting.enabled}} 

                apiVersion: v1
                kind: Service
                metadata:
                    name: "$APP_NAME"
                    labels:
                        app: "$APP_NAME"
                spec:
                    type: LoadBalancer
                    ports:
                    - port: {{{ inputs.containerPort }}}
                      targetPort: http
                      protocol: TCP
                      name: http
                    selector:
                        app: "$APP_NAME"
                        
                {{/inputs.aksCluster.properties.addonProfiles.httpapplicationrouting.enabled}} "  > manifest_{{{IMAGE_NAME}}}.yml


    - uses: azure/k8s-deploy@v1
      with:
        namespace: $NAMESPACE
        manifests: |
          {{{ GITHUB_WORKSPACE/manifest_{{{IMAGE_NAME}}}.yml }}}
        images: |
          $REGISTRY_URL/$IMAGE_NAME:{{=<% %>=}}${{ <% github.sha %> }}<%={{ }}=%>
        imagepullsecrets: |
          $SECRET_NAME