# Node.js with gulp on Linux Web App
# Build a Node.js project using the gulp task runner and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:

on:
  push:
    branches:
      - {{{ sourceRepository.branch }}}

name: Build and deploy Node app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - uses: actions/checkout@master

    - uses: azure/login@v1
      with:
        creds: {{=<% %>=}}${{ secrets.<% targetResource.serviceConnectionId %> }}<%={{ }}=%>
    
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    # install dependencies, build, and test
    - name: npm install, build
      run: |
        npm install
        gulp default --gulpfile gulpfile.js
    
    - uses: azure/appservice-settings@v1
      with:
        app-name: {{{ targetResource.resource.name }}}
        general-settings-json: '{"linuxFxVersion": "NODE|10.10"}' #'General configuration settings as Key Value pairs'
    
    # deploy web app 
    - uses: azure/webapps-deploy@v1
      with:
        app-name: {{{ targetResource.resource.name }}}

    # Azure logout
    - name: logout
      run: |
        az logout